# Use an existing image as a base
FROM alpine

# Metadata (ex: image maintainer)

# Download and install a dependency
# Try to use only 1 RUN instruction with \
# Example:
#   apk update \
#   apk install -y redis
RUN apk add --update redis

# Tell the image what to do when it starts as a container
# Syntax: CMD["command", "arg1", "arg2"]
CMD ["redis-server"]